[PLAYER-4984] Apply Eslint and modify config to make all errors warnings
ooyala/html5-common pull request #97
Opened 2019-04-04 09:50 UTC by MariskaS

2019-04-04 09:54 UTC, ooyala-amohnatkin submitted a review, later dismissed

2019-04-04 12:53 UTC, ooyala-amohnatkin submitted a review, later dismissed

2019-04-06 17:47 UTC, ooyala-amohnatkin commented on js/classes/message_bus.js
> +          const foo = this._dependentList ? this._dependentList[eventName] : '[null]';
maybe something like`blockers`, not `foo`?

2019-04-06 17:52 UTC, ooyala-amohnatkin commented on js/classes/message_bus.js
> +      this._messageHistory.push(_.toArray(args));
`toArray` is redundant

2019-04-06 18:00 UTC, ooyala-amohnatkin requested changes

2019-04-08 14:22 UTC, ooyala-amohnatkin submitted a review, later dismissed

2019-04-08 14:25 UTC, KseniiaSokolovaEpam submitted a review, later dismissed

2019-04-08 14:31 UTC, ALexanderSPB submitted a review, later dismissed

2019-04-10 08:25 UTC, KseniiaSokolovaEpam submitted a review, later dismissed

2019-04-10 10:23 UTC, ALexanderSPB submitted a review, later dismissed

2019-05-15 11:25 UTC, closed without merging

2019-05-15 11:27 UTC, MariskaS commented
All changes are moved to https://github.com/ooyala/html5-common/pull/102